print (" ")
print ("A. INPUT DATA")
print (" ") 
nama = input ("Nama Lengkap : ")
namapanggilan = input ("Nama Panggilan : ")
NPM = input ("NPM : ")
Tempatlahir = input ("Tempat Lahir : ")
Umur = input ("Umur : ")
alamat = input ("Alamat : ")
tlp = input ("Telephone : ")
print (" ")
print ("B. OUTPUT DATA")
print (" ")
print ("Assalamualaikum")
print ("")
print ("Let me introduce my self. My name is ",nama,", but you can call me ",namapanggilan,". My NPM is ",NPM,". I was born in ",Tempatlahir," and iam ",Umur," years old. Iam very glad if you want to invite my house in ",alamat,". So don't forget to call me before with the number ",tlp,"")
print ("")
print ("Thank You.")

